# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('pin_code', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=20)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContactTable')),
            ],
        ),
        migrations.AddField(
            model_name='addresstable',
            name='phone_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContactTable'),
        ),
    ]
