# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160822_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstable',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
